name: Framework Data Import
on:
  push:
    paths:
      - .github/workflows/main.yml
  schedule:
    - cron: '0 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      NEO4J_URI: ${{ secrets.NEO4J_URI }}
      NEO4J_USER: ${{ secrets.NEO4J_USERNAME }}
      NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      
      - name: Fetch Framework Code
        uses: githubocto/flat@v2
        with:
          http_url: https://github.com/hypermodeinc/modus
          downloaded_filename: framework_code.json

      - name: Fetch Framework Docs
        uses: githubocto/flat@v2
        with:
          http_url: https://github.com/hypermodeinc/docs
          downloaded_filename: framework_docs.json

      - name: Neo4j Import
        uses: johnymontana/flat-graph@v1.2
        with:
          neo4j-uri: ${{ secrets.NEO4J_URI }}
          neo4j-user: ${{ secrets.NEO4J_USERNAME }}
          neo4j-password: ${{ secrets.NEO4J_PASSWORD }}
