name: Framework Data Import
on:
  workflow_dispatch:  # This makes it manual trigger only

jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      NEO4J_URI: ${{ secrets.NEO4J_URI }}
      NEO4J_USER: ${{ secrets.NEO4J_USERNAME }}
      NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      
      - name: Clone Framework Code
        run: |
          git clone https://github.com/hypermodeinc/modus.git
          cd modus
          echo "{ \"repository\": \"$(pwd)\", \"files\": $(find . -type f -not -path '*/\.*' -print0 | jq -R -s -c 'split("\u0000")[:-1]')}" > ../framework_code.json
          cd ..

      - name: Clone Framework Docs
        run: |
          git clone https://github.com/hypermodeinc/docs.git
          cd docs
          echo "{ \"repository\": \"$(pwd)\", \"files\": $(find . -type f -not -path '*/\.*' -print0 | jq -R -s -c 'split("\u0000")[:-1]')}" > ../framework_docs.json
          cd ..

      - name: Install jq
        run: sudo apt-get install jq

      - name: Process Files
        run: |
          jq -s '.[0] * .[1]' framework_code.json framework_docs.json > combined_framework_data.json

      - name: Neo4j Import
        uses: johnymontana/flat-graph@v1.2
        with:
          neo4j-uri: ${{ secrets.NEO4J_URI }}
          neo4j-user: ${{ secrets.NEO4J_USERNAME }}
          neo4j-password: ${{ secrets.NEO4J_PASSWORD }}
          file: combined_framework_data.json
